/** @file
 * @brief TurnController declarations and interface documentation. */
#ifndef TURN_CONTROLLER__TURN_CONTROLLER_HPP_
#define TURN_CONTROLLER__TURN_CONTROLLER_HPP_
#include <chrono>
#include <cmath>
#include <memory>
#include <string>
#include <vector>

#include "geometry_msgs/msg/twist.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp/rclcpp.hpp"
#include "tf2/LinearMath/Matrix3x3.h"
#include "tf2/LinearMath/Quaternion.h"
#include "turn_controller/turn_math.hpp"
#include "turn_controller/turn_route.hpp"

/** @brief Execute relative angular waypoints serially without commanding translation. */
class TurnController : public rclcpp::Node
{
public:
  /** @brief Declare simulation parameters and connect control/feedback interfaces.
   * @note Initialization waits for fresh stopped feedback; no laser alignment or translation.
   */
  TurnController();

  /** @brief Report the result of execution to main().
   * @return Zero on completion, two on runtime fault.
   */
  int exit_code() const;

private:
  /** @brief Read and validate a nonnegative numeric ROS parameter.
   * @param[in] name Parameter key chosen by the constructor.
   * @param[in] fallback Default value used when no override is supplied.
   * @return Finite nonnegative value used in control configuration; throws otherwise.
   */
  double nonnegative(const std::string & name, double fallback);

  /** @brief Read a strictly positive numeric parameter.
   * @param[in] name Constructor-supplied ROS parameter key.
   * @param[in] fallback Positive default supplied by the constructor.
   * @return Finite positive value; throws on zero or invalid input.
   */
  double positive(const std::string & name, double fallback);

  /** @brief Validate fresh odom and accumulate signed rotation across the yaw boundary.
   * @param[in] msg Message received by sub_; read pose, frames, stamps and velocity.
   * @note Writes continuous_yaw_, yaw_rate_, receipt_ and stamp_; never writes a target.
   */
  void on_odom(const nav_msgs::msg::Odometry & msg);

  /** @brief Publish zero translation and the requested yaw velocity.
   * @param[in] wz Angular velocity from execute_current_turn() or zero from stop(), rad/s in base frame.
   */
  void publish(double wz);

  /** @brief Publish zero and reset the PID integral and output ramp. */
  void stop();

  /** @brief Stop this controller and request a nonzero process exit.
   * @param[in] reason Fault name from tick()/on_odom(), copied into the ROS logger.
   * @note Base command-timeout braking remains required if transport fails.
   */
  void fail(const char * reason);

  /** @brief Activate the next waypoint frozen during initialization.
   * @param[in] time ROS time forwarded by handle_initialization()/handle_completion(); seeds last_tick_.
   * @note Reads waypoints_[index_] generated by handle_initialization(); writes target_ and phase timing.
   */
  void begin_turn(const rclcpp::Time & time);

  /** @brief Qualify stopped heading, dwell, and advance one completed turn.
   * @param[in] time ROS time forwarded by execute_current_turn(), used for continuous settling/dwell.
   * @param[in] error Target minus continuous_yaw_ computed by execute_current_turn(), radians; checks arrival.
   * @return True when this tick belongs to stopping/dwell; false when PID should run.
   * @note No waypoint completes on angle alone; measured angular and planar speeds must be small.
   */
  bool handle_completion(const rclcpp::Time & time, double error);

  /** @brief Configure reusable turn descriptions and the radians-only ROS override.
   * @note Reads turn_angles from constructor overrides; writes steps_, with no motion side effects.
   */
  void configure_turns();

  /** @brief Stop on missing or expired feedback before any initialization or motion.
   * @param[in] wall Current steady time from tick(), compared with startup and receipt times.
   * @return True when tick() must stop processing; false when accepted feedback is fresh.
   * @note May set exit_code_ and shut down ROS; does not advance any waypoint.
   */
  bool handle_feedback_guard(const std::chrono::steady_clock::time_point & wall);

  /** @brief Qualify the starting pose and generate the entire fixed waypoint sequence once.
   * @param[in] wall Current steady time from tick(), used for startup deadline; advancing feedback stamps qualify the stopped hold.
   * @param[in] time Current ROS time from tick(), forwarded to begin_turn() for PID timing.
   * @return True when initialization consumed the tick; false once the route is already active.
   * @note Reads x_, y_, continuous_yaw_ from on_odom(); writes waypoints_ and starts turn zero.
   */
  bool handle_initialization(
    const std::chrono::steady_clock::time_point & wall, const rclcpp::Time & time);

  /** @brief Execute one tick of the shared turn tracker, independent of route composition.
   * @param[in] wall Steady time from tick(), compared with the active segment deadline.
   * @param[in] time ROS time from tick(), used for PID, settling and dwell intervals.
   * @note Reads frozen target_ and accepted feedback; publishes only angular velocity or zero.
   */
  void execute_current_turn(
    const std::chrono::steady_clock::time_point & wall, const rclcpp::Time & time);

  /** @brief Dispatch feedback guards, initialization, then the shared turn executor. */
  void tick();

  std::vector<turn_controller::TurnStep>
    steps_;  ///< Relative motion descriptions, all stored in radians.
  std::vector<turn_controller::TurnWaypoint>
    waypoints_;  ///< Fixed targets generated once from the initialized pose.
  double x_{};   ///< Last accepted odom x, meters; only records the in-place route origin.
  double y_{};   ///< Last accepted odom y, meters; no translational control is performed.
  std::unique_ptr<turn_controller::AngularPid> pid_;  ///< Angular control state owned by tick().
  rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr pub_;   ///< Sole command output.
  rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr sub_;  ///< Odom input.
  rclcpp::TimerBase::SharedPtr timer_;  ///< Serialized 50 Hz control callback.
  double tolerance_{};                  ///< Accepted heading error, radians.
  double stopped_rate_{};               ///< Accepted stopped odom angular.z magnitude, rad/s.
  double settle_time_{};                ///< Continuous stopped qualification, ROS seconds.
  double dwell_time_{};                 ///< Extra stopped dwell after qualification, ROS seconds.
  double segment_timeout_{};            ///< Per-turn execution budget, steady seconds.
  double startup_timeout_{};            ///< Initial feedback/stopping budget, steady seconds.
  double odom_timeout_{};               ///< Accepted feedback age limit, seconds.
  double continuous_yaw_{};             ///< Accumulated odom yaw, radians; not wrapped at pi.
  double previous_yaw_{};               ///< Previous quaternion-derived yaw, radians.
  double yaw_rate_{};                   ///< Latest odom angular.z in the body frame, rad/s.
  double planar_speed_{};               ///< Latest odom planar speed magnitude, m/s.
  double target_{};                     ///< Frozen turn target, continuous odom radians.
  std::string frame_;                   ///< Accepted odom parent frame.
  std::string child_frame_;             ///< Accepted odom body frame.
  std::size_t index_{};                 ///< Current turn index, advanced only after stopped dwell.
  bool received_{};                     ///< At least one valid fresh odom message has arrived.
  bool started_{};         ///< Stopped initialization passed and first target was frozen.
  bool startup_stable_{};  ///< Startup stopped feedback is being qualified.
  bool settling_{};        ///< Current target is within tolerance with stopped feedback.
  bool dwelling_{};        ///< Settling passed; extra stopped dwell is active.
  int exit_code_{};        ///< main() result: zero completion, two runtime fault.
  rclcpp::Time stamp_{0, 0, RCL_ROS_TIME};       ///< Last accepted feedback header stamp.
  rclcpp::Time last_tick_{0, 0, RCL_ROS_TIME};   ///< Previous advancing control timestamp.
  rclcpp::Time hold_since_{0, 0, RCL_ROS_TIME};  ///< Settling/dwell start, ROS time.
  std::chrono::steady_clock::time_point startup_started_{
    std::chrono::steady_clock::now()};  ///< Startup deadline origin.
  rclcpp::Time startup_stable_stamp_{
    0, 0, RCL_ROS_TIME};  ///< First stopped sample stamp; requires new feedback spanning 0.3 s.
  std::chrono::steady_clock::time_point
    segment_started_{};                              ///< Current turn wall-time deadline origin.
  std::chrono::steady_clock::time_point receipt_{};  ///< Last accepted odom receipt time.
};
#endif
